REPOSITORY_KICS_ARGUMENTS: --exclude-paths dev,.github --fail-on high
REPOSITORY_TRIVY_ARGUMENTS: --severity HIGH,CRITICAL
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
MARKDOWN_MARKDOWNLINT_ARGUMENTS: --ignore dev --disable MD024
COPYPASTE_JSCPD_DISABLE_ERRORS: true
REPOSITORY_CHECKOV_ARGUMENTS: --skip-path api-docs
PRE_COMMANDS:
  - command: "apk add openssl-dev openssl-libs-static cmake gcc g++"
    cwd: "root"
