REPOSITORY_KICS_ARGUMENTS: --exclude-paths dev,.github --fail-on high
REPOSITORY_TRIVY_ARGUMENTS: --severity HIGH,CRITICAL
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
MARKDOWN_MARKDOWNLINT_ARGUMENTS: --disable MD024
COPYPASTE_JSCPD_DISABLE_ERRORS: true
