log_level: info
#auth:
#  oidc:
#    client_id:
#    client_secret:
#    issuer_url:
ttp:
  epix:
    base_url:
    domain:
      name: test
      description: Test domain
    identifier_domain: MPI
    data_source: dummy_safe_source
  gpas:
    base_url:
  timeout: 120
