log_level: info
auth:
  basic:
    username:
    password:
ttp:
  epix:
    base_url:
    domain:
      name: test
      description: Test domain
    identifier_domain: MPI
    data_source: dummy_safe_source
  gpas:
    base_url:

  #  auth:
  #    basic:
  #      username:
  #      password:
  timeout: 120
